name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'This was your first issue! Thank you for contributing!'' first issue'
        pr-message: 'This was your first Pull Request! Thank you for contributing!'' first pr'
